language: php
php:
  - '7.1'

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_success:
- travis_retry php vendor/bin/coveralls
