version: '2'

services:
    nginx:
        image: nginx:1.11
        volumes:
            - ./:/usr/share/nginx/html/
            - ./build/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /usr/share/nginx/html/
        ports:
            - 8080:80
        depends_on:
            - php
            - postgres

    php:
        image: ricardotulio/php:7.1-fpm
        env_file: .env
        volumes:
            - ./:/usr/share/nginx/html/
        working_dir: /usr/share/nginx/html/
    
    postgres:
        image: postgres:9.6.2
        env_file: .env
        ports:
            - 5432:5432

volumes:
    db:
        driver: local
